# Generated by Django 4.2.1 on 2023-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
