# Generated by Django 5.0 on 2024-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='experience',
            field=models.CharField(choices=[('fresher', 'fresher')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.CharField(choices=[('Cloud Engineer', 'Cloud Engineer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='skills',
            field=models.CharField(choices=[('AWS', 'AWS')], max_length=100),
        ),
    ]
