ROLE_CHOICES=(
    ('DevOps Engineer', 'DevOps Engineer'),
    ('Data Scientist', 'Data Scientist'),
    ('Data Engineer', 'Data Engineer'),
    ('Software Engineer', 'Software Engineer'),
    ('Cloud Engineer', 'Cloud Engineer'),
    ('Machine Learning Engineer', 'Machine Learning Engineer'),
    ('Artificial Intelligence Engineer', 'Artificial Intelligence Engineer'),
    ('Full Stack Developer', 'Full Stack Developer'),
    ('Frontend Developer', 'Frontend Developer'),
    ('Backend Developer', 'Backend Developer'),
    ('Systems Administrator', 'Systems Administrator'),
    ('Network Engineer', 'Network Engineer'),
    ('Security Engineer', 'Security Engineer'),
    ('Database Administrator', 'Database Administrator'),
    ('Quality Assurance Engineer', 'Quality Assurance Engineer'),
    ('UI/UX Designer', 'UI/UX Designer'),
    ('Technical Support Engineer', 'Technical Support Engineer'),
    ('Business Intelligence Analyst', 'Business Intelligence Analyst'),
    ('Product Manager (Technical)', 'Product Manager (Technical)'),
    ('IT Project Manager', 'IT Project Manager')
) 
EXP_CHOICES=(
    ('fresher','fresher'),
    ('1-3','1-3'),
    ('3-6','3-6'),
    ('6-9','6-9'),
    ('above 9','above 9'),
)

SKILLS_CHOICES=(
     ('AWS', 'AWS'),
     ('Azure', 'Azure'),
     ('GCP', 'GCP'),
    ('Python', 'Python'),
    ('Java', 'Java'),
    ('C++', 'C++'),
    ('JavaScript', 'JavaScript'),
    ('SQL', 'SQL'),
    ('NoSQL', 'NoSQL'),
    ('Docker', 'Docker'),
    ('Kubernetes', 'Kubernetes'),
    ('Git', 'Git'),
    ('HTML', 'HTML'),
    ('CSS', 'CSS'),
    ('React', 'React'),
    ('Angular', 'Angular'),
    ('Node.js', 'Node.js'),
    ('Flask', 'Flask'),
    ('Django', 'Django'),
    ('TensorFlow', 'TensorFlow'),
    ('PyTorch', 'PyTorch'),
    ('Spark', 'Spark'),
    ('Hadoop', 'Hadoop'),
    ('Machine Learning', 'Machine Learning'),
    ('Deep Learning', 'Deep Learning'),
    ('Data Analysis', 'Data Analysis'),
    ('Data Visualization', 'Data Visualization'),
    ('Linux', 'Linux'),
    ('Windows Server', 'Windows Server'),
    ('Network Security', 'Network Security'),
    ('Cybersecurity', 'Cybersecurity'),
    ('Agile Methodologies', 'Agile Methodologies'),
    ('Scrum', 'Scrum'),
    ('Project Management', 'Project Management'),
    ('Leadership', 'Leadership'),
    ('Communication', 'Communication')
)